name: UNIX-LAB.ORG
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
  "tables", "with_toc_data", "underline", "highlight", "quote",
  "footnotes", "strikethroug", "space_after_headers"]
pygments: true

timezone: Europe/Moscow
encoding: UTF-8

# paginate: 6
# paginate_path: 'page:num'
paginate_path: #none
relative_permalinks: false
permalink: /posts/:title
tag_page_layout: tag_page
tag_page_dir: tags

# future: false
safe: false
lsi: false
excerpt_separator: "\n\n"

destination: public

title: UNIX-LAB.ORG
description: Блог об операционных системах, open source и программировании
url: http://www.unix-lab.org
# url: http://localhost:4000

# imgdir: /images

exclude: ['Gemfile*', 'README']
keep_files: ['.gitkeep']

## for openshift
auto: false
server: false
#
# To preview your new post, simply run the jekyll serve command with the --drafts flag.
# $ gem update jekyll
